#!/bin/bash

#set -e

ok() {
	echo -e "\e[1;32m$1\e[0m"
}

err() {
	echo -e "\e[31m$1\e[0m"
}

do_test() {
	NAME=$1
	printf %-20s $NAME

	if grep -q csrr ../src/test/compliance/${NAME}.S; then
		ok "SKIP"
		return
	fi

	(
	make -C ../src/ clean
	make -C ../src/ SSRC=test/compliance/${NAME}.S
	make clean
	make > mem.dump
	) > /tmp/build.out 2>&1

	if [ ! -r ../src/t.elf ]; then
		err "BUILD"
		return
	fi

	FROM=`nm ../src/t.elf | egrep test.+res | sort | head -1 | awk '{print $1}'`
	TO=`nm ../src/t.elf | egrep test.+res | sort | tail -1 | awk '{print $1}'`

	if [ "$FROM" == "" -o "$TO" == "" ]; then
		err "EXEC"
		return
	fi

	FROM=$((16#$FROM))
	TO=$((16#$TO))

	(
	for i in `seq $FROM $(($TO+20))`; do
		a=`printf "%08x" $i`
		grep "mem $a" mem.dump | awk '{print $3}'
	done
	) > /tmp/out

	LINES=`wc -l ../src/test/ref/${NAME} | awk '{print $1}'`
	diff -u <(head -$LINES /tmp/out) ../src/test/ref/${NAME} > /tmp/diff.out
	if [ "$?" == "0" ]; then
		ok OK
	else
		err FAIL
	fi
}

if [ "$1" != "" ]; then
	do_test I-$1-01
	cat /tmp/build.out
	cat /tmp/diff.out
else
	TESTS=`cd ../src/test/ref; ls`
	for TEST in $TESTS; do
		do_test $TEST
	done
fi
