#!/bin/bash

PATH_CTS=../riscv-compliance/riscv-test-suite/rv32i

#set -e

ok() {
	echo -e "\e[1;32m$1\e[0m"
}

err() {
	echo -e "\e[31m$1\e[0m"
}

do_test() {
	NAME=$1
	printf %-20s $NAME

	SRC=${PATH_CTS}/src/${NAME}.S
	REF=${PATH_CTS}/references/${NAME}.reference_output

	if grep -q csrr ${SRC}; then
		ok "SKIP"
		return
	fi

	(
	make clean

	make -C ../src/ SSRC=${SRC} t.asm
	make sim > mem.dump
	) > /tmp/build.out 2>&1

	if [ ! -r ../src/t.elf ]; then
		err "BUILD"
		return
	fi

	FROM=`nm ../src/t.elf | egrep test.+res | sort | head -1 | awk '{print $1}'`

	if [ "$FROM" == "" ]; then
		err "EXEC"
		return
	fi

	COUNT=`wc -l ${REF} | awk '{print $1}'`
	FROM=$((16#$FROM))
	TO=$(($FROM + $COUNT*4 - 4))

	(
	for i in `seq $FROM $TO`; do
		a=`printf "%08x" $i`
		grep "mem $a" mem.dump | awk '{print $3}'
	done
	) > /tmp/out

	diff -u ${REF} /tmp/out > /tmp/diff.out
	if [ "$?" == "0" ]; then
		ok OK
	else
		err FAIL
	fi
}

if [ "$1" != "" ]; then
	do_test I-$1-01
	cat /tmp/build.out
	cat /tmp/diff.out
else
	TESTS=`cd ${PATH_CTS}/src && ls | sed -e 's/.S$//'`
	for TEST in $TESTS; do
		do_test $TEST
	done
fi
